import type { CSSProperties } from 'react';

export const styles: Record<string, CSSProperties> = {
  container: {
    minHeight: '100vh',
    backgroundColor: '#f8f9fa',
  },

  // 欢迎界面样式 - 简洁卡片
  welcomeContainer: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
  },
  welcomeTopActions: {
    position: 'fixed',
    top: '20px',
    right: '20px',
    zIndex: 3,
  },
  settingsButton: {
    height: '36px',
    padding: '0 14px',
    borderRadius: '18px',
    border: '1px solid rgba(255, 255, 255, 0.65)',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    color: '#ffffff',
    fontSize: '0.875rem',
    fontWeight: '600',
    cursor: 'pointer',
    backdropFilter: 'blur(6px)',
  },
  emptyState: {
    textAlign: 'center',
    padding: '48px',
    backgroundColor: 'white',
    borderRadius: '8px',
  },
  emptyIcon: {
    fontSize: '4rem',
    marginBottom: '16px',
  },
  emptyTitle: {
    fontSize: '1.75rem',
    fontWeight: '600',
    color: '#1a202c',
    marginBottom: '8px',
  },
  emptyText: {
    fontSize: '1rem',
    color: '#4a5568',
    marginBottom: '24px',
  },
  emptyHint: {
    fontSize: '0.875rem',
    color: '#64748b',
    marginBottom: '24px',
  },
  welcomeButtons: {
    display: 'flex',
    gap: '12px',
    justifyContent: 'center',
  },
  fileButton: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    padding: '12px 24px',
    background: '#667eea',
    color: 'white',
    border: 'none',
    borderRadius: '6px',
    fontSize: '0.9375rem',
    fontWeight: '500',
    cursor: 'pointer',
  },
  folderButton: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    padding: '12px 24px',
    background: '#48bb78',
    color: 'white',
    border: 'none',
    borderRadius: '6px',
    fontSize: '0.9375rem',
    fontWeight: '500',
    cursor: 'pointer',
  },
  settingsOverlay: {
    position: 'fixed',
    inset: 0,
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '20px',
    zIndex: 1000,
  },
  settingsModal: {
    width: 'min(480px, 100%)',
    backgroundColor: '#ffffff',
    borderRadius: '10px',
    boxShadow: '0 20px 40px rgba(15, 23, 42, 0.25)',
    overflow: 'hidden',
  },
  settingsHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '16px 20px',
    borderBottom: '1px solid #e2e8f0',
  },
  settingsTitle: {
    fontSize: '1rem',
    fontWeight: '600',
    color: '#1a202c',
  },
  settingsCloseButton: {
    padding: '6px 12px',
    border: '1px solid #e2e8f0',
    borderRadius: '4px',
    background: '#ffffff',
    color: '#4a5568',
    cursor: 'pointer',
    fontSize: '0.875rem',
  },
  settingsBody: {
    padding: '16px 20px 20px',
  },
  settingsRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
  },
  settingsLabelGroup: {
    textAlign: 'left',
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  settingsLabel: {
    fontSize: '0.9375rem',
    fontWeight: '600',
    color: '#1e293b',
  },
  settingsDescription: {
    fontSize: '0.8125rem',
    color: '#64748b',
  },
  settingsToggle: {
    width: '18px',
    height: '18px',
    cursor: 'pointer',
  },

  // 加载界面
  loadingContainer: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f8f9fa',
  },
  spinner: {
    width: '40px',
    height: '40px',
    border: '3px solid #e2e8f0',
    borderTop: '3px solid #667eea',
    borderRadius: '50%',
    marginBottom: '16px',
  },
  loadingText: {
    fontSize: '1rem',
    color: '#4a5568',
  },

  // 错误界面
  errorContainer: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '20px',
    backgroundColor: '#f8f9fa',
  },
  error: {
    textAlign: 'center',
    color: '#c53030',
  },
  backButton: {
    marginTop: '16px',
    padding: '8px 16px',
    background: '#c53030',
    color: 'white',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
  },

  // 查看器主布局
  viewerContainer: {
    height: '100vh',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#f8f9fa',
    overflow: 'hidden',
  },

  // 顶部工具栏 - 简洁
  toolbar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 24px',
    backgroundColor: 'white',
    borderBottom: '1px solid #e2e8f0',
    flexShrink: 0,
  },
  toolbarLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
  },
  toolbarRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  coursewareName: {
    fontSize: '1rem',
    fontWeight: '500',
    color: '#1a202c',
  },
  slideInfo: {
    fontSize: '0.875rem',
    color: '#718096',
  },
  clearButton: {
    padding: '6px 12px',
    background: 'transparent',
    color: '#718096',
    border: 'none',
    fontSize: '0.875rem',
    cursor: 'pointer',
  },
  issueButton: {
    padding: '6px 12px',
    background: '#edf2f7',
    color: '#2d3748',
    border: '1px solid #e2e8f0',
    borderRadius: '4px',
    fontSize: '0.875rem',
    cursor: 'pointer',
  },

  // 主内容区
  mainContent: {
    display: 'flex',
    flex: 1,
    overflow: 'hidden',
  },

  // 侧边栏 - 简洁
  sidebar: {
    width: '240px',
    minWidth: '240px',
    backgroundColor: 'white',
    borderRight: '1px solid #e2e8f0',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  sidebarHeader: {
    padding: '12px 16px',
    fontSize: '0.75rem',
    fontWeight: '600',
    color: '#718096',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
    flexShrink: 0,
  },
  slideList: {
    flex: 1,
    overflowY: 'auto',
    padding: '8px',
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  slideTab: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '10px 12px',
    backgroundColor: 'transparent',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    textAlign: 'left',
    flexShrink: 0,
  },
  slideTabActive: {
    backgroundColor: '#edf2f7',
  },
  slideTabStack: {
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: '6px',
  },
  slideTabMetaRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  slideTabNumber: {
    width: '24px',
    height: '24px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#e2e8f0',
    borderRadius: '4px',
    fontSize: '0.75rem',
    fontWeight: '600',
    color: '#4a5568',
  },
  slideTabInfo: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
    flex: 1,
  },
  slideTabTitle: {
    fontSize: '0.875rem',
    color: '#1a202c',
  },
  slideTabSize: {
    fontSize: '0.75rem',
    color: '#a0aec0',
  },
  slideTabPreviewWrapper: {
    marginTop: 0,
    padding: 0,
    borderRadius: 0,
    backgroundColor: 'transparent',
  },
  slideTabPreviewViewport: {
    height: '56px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    borderRadius: '0',
    backgroundColor: 'transparent',
  },
  slideTabPreviewContent: {
    pointerEvents: 'none',
  },
  slideTabPreviewImage: {
    maxWidth: '100%',
    maxHeight: '100%',
    display: 'block',
  },

  // 幻灯片查看器区域
  slideViewerContainer: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    position: 'relative',
  },
  slideContainer: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#e2e8f0',
    overflow: 'auto',
    padding: '24px',
  },
  slideWrapper: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },

  // 问题弹窗
  modalOverlay: {
    position: 'fixed',
    inset: 0,
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '20px',
    zIndex: 1000,
  },
  modalCard: {
    width: 'min(920px, 100%)',
    maxHeight: 'min(80vh, 760px)',
    backgroundColor: '#ffffff',
    borderRadius: '10px',
    boxShadow: '0 20px 40px rgba(15, 23, 42, 0.25)',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  modalHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '16px 20px',
    borderBottom: '1px solid #e2e8f0',
  },
  modalTitle: {
    fontSize: '1rem',
    fontWeight: '600',
    color: '#1a202c',
  },
  modalCloseButton: {
    padding: '6px 12px',
    border: '1px solid #e2e8f0',
    borderRadius: '4px',
    background: '#ffffff',
    color: '#4a5568',
    cursor: 'pointer',
    fontSize: '0.875rem',
  },
  modalSummary: {
    display: 'flex',
    gap: '16px',
    flexWrap: 'wrap',
    padding: '12px 20px',
    borderBottom: '1px solid #edf2f7',
    backgroundColor: '#f8fafc',
    color: '#475569',
    fontSize: '0.875rem',
  },
  issueFilterBar: {
    display: 'flex',
    gap: '8px',
    flexWrap: 'wrap',
    padding: '10px 20px',
    borderBottom: '1px solid #edf2f7',
    backgroundColor: '#ffffff',
  },
  issueFilterButton: {
    padding: '4px 10px',
    border: '1px solid #cbd5e1',
    borderRadius: '999px',
    backgroundColor: '#ffffff',
    color: '#475569',
    fontSize: '0.75rem',
    cursor: 'pointer',
  },
  issueFilterButtonActive: {
    backgroundColor: '#e2e8f0',
    color: '#1e293b',
    borderColor: '#94a3b8',
  },
  modalEmpty: {
    padding: '28px 20px',
    color: '#64748b',
    fontSize: '0.9375rem',
  },
  issueList: {
    overflowY: 'auto',
    padding: '12px 20px 20px',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  issueItem: {
    border: '1px solid #e2e8f0',
    borderRadius: '8px',
    padding: '12px',
    backgroundColor: '#ffffff',
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  issueItemHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    flexWrap: 'wrap',
  },
  issueBadge: {
    fontSize: '0.75rem',
    fontWeight: '600',
    padding: '2px 8px',
    borderRadius: '999px',
    backgroundColor: '#fff7ed',
    color: '#9a3412',
    border: '1px solid #fed7aa',
  },
  issueMeta: {
    fontSize: '0.75rem',
    color: '#64748b',
  },
  issueName: {
    fontSize: '0.875rem',
    color: '#1e293b',
    fontWeight: '500',
  },
  issueValue: {
    fontSize: '0.8125rem',
    color: '#475569',
    lineHeight: 1.4,
    wordBreak: 'break-all',
  },

  // 底部信息栏 - 贴底
  slideInfoBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '8px 16px',
    backgroundColor: 'white',
    borderTop: '1px solid #e2e8f0',
    fontSize: '0.75rem',
    color: '#718096',
    zIndex: 10,
  },
  slideInfoItems: {
    display: 'flex',
    alignItems: 'center',
    gap: '20px',
    overflowX: 'auto',
    paddingRight: '12px',
  },
  infoItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },
  infoLabel: {
    color: '#a0aec0',
  },
  colorPreview: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },
  colorBox: {
    width: '12px',
    height: '12px',
    borderRadius: '2px',
    border: '1px solid #e2e8f0',
  },
  slidePanelToggleButton: {
    height: '26px',
    padding: '0 10px',
    border: '1px solid #cbd5e1',
    borderRadius: '4px',
    backgroundColor: '#f8fafc',
    color: '#334155',
    fontSize: '0.75rem',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    flexShrink: 0,
  },
  slidePagerControls: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    flexShrink: 0,
  },
  slidePagerButton: {
    width: '26px',
    height: '26px',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: '1px solid #cbd5e1',
    borderRadius: '4px',
    backgroundColor: '#f8fafc',
    color: '#334155',
    fontSize: '0.75rem',
    cursor: 'pointer',
    flexShrink: 0,
  },
  slidePagerButtonDisabled: {
    color: '#94a3b8',
    borderColor: '#e2e8f0',
    backgroundColor: '#f1f5f9',
    cursor: 'not-allowed',
  },
  slidePanelOverlay: {
    position: 'absolute',
    inset: 0,
    backgroundColor: 'rgba(15, 23, 42, 0.08)',
    zIndex: 15,
  },
  slideFloatingPanel: {
    position: 'absolute',
    top: '16px',
    right: '16px',
    bottom: '52px',
    width: '200px',
    backgroundColor: '#ffffff',
    border: '1px solid #e2e8f0',
    borderRadius: '8px',
    boxShadow: '0 14px 28px rgba(15, 23, 42, 0.16)',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    zIndex: 20,
  },
};
